### ISSUE TITLE
Assign client. & server.Network.ASNumber (and related ASN fields)

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/uuid-annotator#9]
Standard columns for client and server geo & network annotations include the ASN information. Right now uuid-annotator unconditionally saves 'null' information for all clients and server IPs.

In addition to {client,server}.Geo, the .Network fields should also be assigned:

{client,server}
 * Network
   - NetBlock
   - ASNumber
   - ASName

**Comment by mehtab11** [comment]
Done.
